KBV-774: Capture duration of experian requests
alphagov/di-ipv-cri-kbv-api pull request #155
Opened 2022-08-02 11:27 UTC by jkunle

## Proposed changes

Even though X-ray provides subsegments that show the actual duration of the request being investigated. There isn't an easy way to extract this information. This PR is needed to be able to capture the actual duration of the experian requests i.e. the request for question and the duration of the request when submitting answers

see: https://govukverify.atlassian.net/browse/KBV-774

### What changed

Add more metric and logging for experian requests

### Why did it change

More information required to the extract details at the level of the method call

### Other considerations
It maybe that just logging would be enough, however added metric here as well if it proves not be useful would remove in future PR

2022-08-02 14:20 UTC, tal-nagra reviewed
Please take a look at ( if you haven't already done so ):
https://awslabs.github.io/aws-lambda-powertools-java/core/tracing/
Apparently the `@Tracing` annotation can automatically record a sub-segment for any method ??

2022-08-08 13:07 UTC, tal-nagra requested changes

2022-08-08 13:07 UTC, tal-nagra commented on lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/gateway/KBVGateway.java
> +    private void logTimeTaken(Instant start, Instant end, String requestType) {
remove this method & pass the duration to the sendResultMetric method

2022-08-08 13:07 UTC, tal-nagra commented on lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/gateway/KBVGateway.java
> +        TracingUtils.putAnnotation(EXPERIAN_IIQ_REQUEST, EXPERIAN_START_AUTHENTICATION_ATTEMPT);
If this putAnnotation method isn't serving any purpose at the moment then it can be removed

2022-08-08 13:07 UTC, tal-nagra commented on lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/gateway/KBVGateway.java
> +        TracingUtils.putAnnotation(EXPERIAN_IIQ_REQUEST, EXPERIAN_RESPONSE_TO_QUESTIONS);
If this putAnnotation method isn't serving any purpose at the moment then it can be removed

2022-08-08 13:07 UTC, tal-nagra commented on lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/gateway/KBVGateway.java
> +        logTimeTaken(start, end, EXPERIAN_START_AUTHENTICATION_ATTEMPT);
remove this line

2022-08-08 13:07 UTC, tal-nagra commented on lib/src/main/java/uk/gov/di/ipv/cri/kbv/api/gateway/KBVGateway.java
> +        logTimeTaken(start, end, EXPERIAN_RESPONSE_TO_QUESTIONS);
remove this line

2022-08-09 12:03 UTC, tal-nagra approved these changes

2022-08-09 12:32 UTC, MattBidewell approved these changes

2022-08-09 12:36 UTC, merged