BAU: parameterise deploy script
alphagov/di-ipv-cri-kbv-api pull request #216
Opened 2022-12-02 11:24 UTC by jkunle

## Proposed changes

This PR allows the deploy script to be receive a different common api stack and to specify a different secret prefix if required without having to change the deploy script itself.

### What changed

The local `deploy.sh` script

### Why did it change

To prevent custom changes to `deploy.sh` to be pushed

- [ ] Update [README](./blob/main/README.md) with any new instructions or tasks

2022-12-02 16:36 UTC, tal-nagra requested changes

2022-12-02 16:36 UTC, tal-nagra commented on deploy.sh
> +secret_prefix="${3:-kbv-cri-api}"
we should make the `common_stack_name` and `secret_prefix` optional parameters that default to the values on line 26 and 27 if they are not specified
In a similar manner to:
https://github.com/alphagov/di-ipv-cri-common-lambdas/blob/d5a5eeb8fb3557edfd9dc40989063056c75ce4b6/deploy.sh#L23

2022-12-02 16:36 UTC, tal-nagra commented on README.md
> +Supply a required stack name in place of `your-stack-name` above, the `CommonStackName` and `SecretPrefix`
Update to indicate the common stack name & secret prefix are optional parameters

2022-12-02 17:12 UTC, tal-nagra submitted a review, later dismissed

2022-12-02 17:27 UTC, techaman-m approved these changes

2022-12-05 10:49 UTC, kiejgordon approved these changes
Looks good to me

2022-12-05 10:53 UTC, merged