(DO NOT MERGE) OJ-1105: Updated audit event from "THIRD_PARTY_REQUEST_ENDED" to "RESPONSE_RECEIVED"
alphagov/di-ipv-cri-kbv-api pull request #268
Opened 2023-06-07 09:13 UTC by surajkumar

## Proposed changes

### What changed

### Why did it change
TXMA are requesting we change the name of "IPV_KBV_CRI_THIRD_PARTY_REQUEST_ENDED" to "IPV_KBV_CRI_RESPONSE_RECEIVED". This is for consistency with passport CRI.

### Issue tracking

- [OJ-1105](https://govukverify.atlassian.net/browse/OJ-1105)

## Checklists

### Environment variables or secrets

- [X] No environment variables or secrets were added or changed

2023-06-07 13:27 UTC, merlinc requested changes

2023-06-07 13:27 UTC, merlinc commented on lambdas/answer/src/test/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandlerTest.java
> -                        eq(AuditEventType.THIRD_PARTY_REQUEST_ENDED),
Can we change the test to also include `RESPONSE_RECEIVED`? 

When we remove the `THIRD_PARTY_REQUEST_ENDED` event we can then remove the associated tests.

2023-06-09 08:37 UTC, jkunle commented on lambdas/answer/src/test/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandlerTest.java
> +                        eq(AuditEventType.RESPONSE_RECEIVED),
Please could you still have the verify on`THIRD_PARTY_REQUEST_ENDED` in addition to the one on RESPONSE_RECEIVED

2023-06-09 11:17 UTC, jkunle approved these changes

2023-06-09 11:21 UTC, merged